---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Distribution of Restaurant's Score in 2017

```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec |> 
  drop_na() 


rest_inspec |> 
  filter(year(inspection_date) == '2017') |> 
  plot_ly(x = ~inspection_date, y = ~score, alpha = 0.4,
          type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Number of Inspections within Each Borough in New York

```{r}
rest_inspec |> 
  filter(boro !='Missing') |> 
  count(boro) |> 
  mutate(boro = fct_reorder(boro, n)) |>
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar")
```

### Chart C: Distribution of Restaurant’s Inspection Score from 2011 to 2017

```{r warning = FALSE}
data("rest_inspec")

rest_inspec |> 
  mutate(year = year(inspection_date)) |> 
  filter(year %in% c('2013', '2014', '2015', '2016', '2017')) |> 
  plot_ly(x = ~year, y = ~score, type = "box")
```

